[package]
name = "sim8086"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dev-dependencies]
assert_cmd = "2.0.12"
predicates = "3.0.3"
tempfile = "3.8.0"

[dependencies]
bytes = "1.5.0"
anyhow = "1.0.40"
